version: "3.9"

services:
  postgres:
    image: ${TIMESCALE_IMAGE}
    container_name: pg-timescale
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - ./postgres/initdb:/docker-entrypoint-initdb.d
    ports:
      - "${POSTGRES_PORT}:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB} -h 127.0.0.1" ]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - app_net

  grafana:
    image: ${GRAFANA_IMAGE}
    container_name: grafana
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      GF_SECURITY_ADMIN_USER: ${GRAFANA_USER}
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_PASSWORD}
      GF_USERS_ALLOW_SIGN_UP: "false"
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - grafana_storage:/var/lib/grafana
    ports:
      - "${GRAFANA_PORT}:3000"
    networks:
      - app_net

  ingestor:
    build: ./ingestor
    container_name: ingestor
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      # DB
      PGHOST: postgres
      PGPORT: 5432
      PGDATABASE: observability
      PGUSER: ${POSTGRES_USER}
      PGPASSWORD: ${POSTGRES_PASSWORD}

      # MeteoSIX
      METEOSIX_API_KEY: ${METEOSIX_API_KEY}
      METEOSIX_BASE_URL: ${METEOSIX_BASE_URL}
      METEOSIX_OPERATION: ${METEOSIX_OPERATION}
      METEOSIX_FORMAT: ${METEOSIX_FORMAT}
      METEOSIX_LANG: ${METEOSIX_LANG}
      METEOSIX_COORDS: ${METEOSIX_COORDS}

      # AEMET
      AEMET_API_KEY: ${AEMET_API_KEY}
      AEMET_BASE_URL: ${AEMET_BASE_URL}

      # Scheduler + caché
      POLL_SECONDS: ${POLL_SECONDS}
      POLL_AEMET_SECONDS: ${POLL_AEMET_SECONDS}
      CACHE_TTL_SECONDS: ${CACHE_TTL_SECONDS}
      CACHE_DIR: /app/cache
    volumes:
      - ingestor_cache:/app/cache
    networks:
      - app_net
volumes:
  grafana_storage:
  ingestor_cache:


networks:
  app_net:
    driver: bridge
