apiVersion: 1
contactPoints:
  - orgId: 1
    name: 'Discord Alertas'
    receivers:
      - uid: 'discord_webhook'
        type: discord
        settings:
          url: 'https://webhook.site/placeholder-sustituye-esto-por-tu-webhook'
          message: |-
            {{ template "default.message" . }}
            {{ if gt (len .Alerts.Firing) 0 }}
            **Alertas Activas:**
            {{ range .Alerts.Firing }}
            - **{{ .Labels.alertname }}** (Zona **{{ .Labels.zona }}**) -> {{ .Annotations.summary }}
            {{ end }}
            {{ end }}
